[project]
name = "med-asg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hydra-core>=1.3.2",
    "omegaconf>=2.3.0",
    "pandas>=2.2.2",
    "openpyxl>=3.1.2",
    "pydantic>=2.6.4",
    "argostranslate>=1.9.1",
]
