data:
    excel_path: "data/Case Study - Data & AI Engineer.xlsx"
    sheets:
        - "1.1 RX 目标市场"
        - "1.2 电子商务 目标市场"
        - "1.3 Device"
        - "1.4 Retail"
        - "1.5 CSO&DSO 广阔市场"
        - "1.6 非目标市场"
        - "4 产品 DIM"
